version: 1
update_configs:
  - package_manager: "python"
    directory: "/backend"
    update_schedule: "live"
    default_labels:
      - "dependencies"
      - "python"
    commit_message:
      prefix: "Crowdbotics"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependencies"
      - "javascript"
    commit_message:
      prefix: "Crowdbotics"